import { db } from '@/db';
import { meals } from '@/db/schema';

async function main() {
    const sampleMeals = [
        // Diet Chart 1 - Meals
        {
            diet_chart_id: 1,
            meal_type: 'breakfast',
            meal_time: '7:00 AM',
            total_calories: 375.0,
            total_protein: 15.0,
            total_carbs: 50.0,
            total_fat: 12.5,
            created_at: new Date('2024-01-15').toISOString(),
        },
        {
            diet_chart_id: 1,
            meal_type: 'mid_morning',
            meal_time: '10:30 AM',
            total_calories: 150.0,
            total_protein: 6.0,
            total_carbs: 20.0,
            total_fat: 5.0,
            created_at: new Date('2024-01-15').toISOString(),
        },
        {
            diet_chart_id: 1,
            meal_type: 'lunch',
            meal_time: '1:00 PM',
            total_calories: 525.0,
            total_protein: 21.0,
            total_carbs: 70.0,
            total_fat: 17.5,
            created_at: new Date('2024-01-15').toISOString(),
        },
        {
            diet_chart_id: 1,
            meal_type: 'evening',
            meal_time: '4:30 PM',
            total_calories: 150.0,
            total_protein: 6.0,
            total_carbs: 20.0,
            total_fat: 5.0,
            created_at: new Date('2024-01-15').toISOString(),
        },
        {
            diet_chart_id: 1,
            meal_type: 'dinner',
            meal_time: '7:30 PM',
            total_calories: 300.0,
            total_protein: 12.0,
            total_carbs: 40.0,
            total_fat: 10.0,
            created_at: new Date('2024-01-15').toISOString(),
        },

        // Diet Chart 2 - Meals
        {
            diet_chart_id: 2,
            meal_type: 'breakfast',
            meal_time: '7:00 AM',
            total_calories: 450.0,
            total_protein: 18.0,
            total_carbs: 60.0,
            total_fat: 15.0,
            created_at: new Date('2024-01-16').toISOString(),
        },
        {
            diet_chart_id: 2,
            meal_type: 'mid_morning',
            meal_time: '10:30 AM',
            total_calories: 180.0,
            total_protein: 7.2,
            total_carbs: 24.0,
            total_fat: 6.0,
            created_at: new Date('2024-01-16').toISOString(),
        },
        {
            diet_chart_id: 2,
            meal_type: 'lunch',
            meal_time: '1:00 PM',
            total_calories: 630.0,
            total_protein: 25.2,
            total_carbs: 84.0,
            total_fat: 21.0,
            created_at: new Date('2024-01-16').toISOString(),
        },
        {
            diet_chart_id: 2,
            meal_type: 'evening',
            meal_time: '4:30 PM',
            total_calories: 180.0,
            total_protein: 7.2,
            total_carbs: 24.0,
            total_fat: 6.0,
            created_at: new Date('2024-01-16').toISOString(),
        },
        {
            diet_chart_id: 2,
            meal_type: 'dinner',
            meal_time: '7:30 PM',
            total_calories: 360.0,
            total_protein: 14.4,
            total_carbs: 48.0,
            total_fat: 12.0,
            created_at: new Date('2024-01-16').toISOString(),
        },

        // Diet Chart 3 - Meals
        {
            diet_chart_id: 3,
            meal_type: 'breakfast',
            meal_time: '7:00 AM',
            total_calories: 387.5,
            total_protein: 15.5,
            total_carbs: 51.7,
            total_fat: 12.9,
            created_at: new Date('2024-01-17').toISOString(),
        },
        {
            diet_chart_id: 3,
            meal_type: 'mid_morning',
            meal_time: '10:30 AM',
            total_calories: 155.0,
            total_protein: 6.2,
            total_carbs: 20.7,
            total_fat: 5.2,
            created_at: new Date('2024-01-17').toISOString(),
        },
        {
            diet_chart_id: 3,
            meal_type: 'lunch',
            meal_time: '1:00 PM',
            total_calories: 542.5,
            total_protein: 21.7,
            total_carbs: 72.3,
            total_fat: 18.1,
            created_at: new Date('2024-01-17').toISOString(),
        },
        {
            diet_chart_id: 3,
            meal_type: 'evening',
            meal_time: '4:30 PM',
            total_calories: 155.0,
            total_protein: 6.2,
            total_carbs: 20.7,
            total_fat: 5.2,
            created_at: new Date('2024-01-17').toISOString(),
        },
        {
            diet_chart_id: 3,
            meal_type: 'dinner',
            meal_time: '7:30 PM',
            total_calories: 310.0,
            total_protein: 12.4,
            total_carbs: 41.3,
            total_fat: 10.3,
            created_at: new Date('2024-01-17').toISOString(),
        },

        // Diet Chart 4 - Meals
        {
            diet_chart_id: 4,
            meal_type: 'breakfast',
            meal_time: '7:00 AM',
            total_calories: 525.0,
            total_protein: 21.0,
            total_carbs: 70.0,
            total_fat: 17.5,
            created_at: new Date('2024-01-18').toISOString(),
        },
        {
            diet_chart_id: 4,
            meal_type: 'mid_morning',
            meal_time: '10:30 AM',
            total_calories: 210.0,
            total_protein: 8.4,
            total_carbs: 28.0,
            total_fat: 7.0,
            created_at: new Date('2024-01-18').toISOString(),
        },
        {
            diet_chart_id: 4,
            meal_type: 'lunch',
            meal_time: '1:00 PM',
            total_calories: 735.0,
            total_protein: 29.4,
            total_carbs: 98.0,
            total_fat: 24.5,
            created_at: new Date('2024-01-18').toISOString(),
        },
        {
            diet_chart_id: 4,
            meal_type: 'evening',
            meal_time: '4:30 PM',
            total_calories: 210.0,
            total_protein: 8.4,
            total_carbs: 28.0,
            total_fat: 7.0,
            created_at: new Date('2024-01-18').toISOString(),
        },
        {
            diet_chart_id: 4,
            meal_type: 'dinner',
            meal_time: '7:30 PM',
            total_calories: 420.0,
            total_protein: 16.8,
            total_carbs: 56.0,
            total_fat: 14.0,
            created_at: new Date('2024-01-18').toISOString(),
        },

        // Diet Chart 5 - Meals
        {
            diet_chart_id: 5,
            meal_type: 'breakfast',
            meal_time: '7:00 AM',
            total_calories: 400.0,
            total_protein: 16.0,
            total_carbs: 53.3,
            total_fat: 13.3,
            created_at: new Date('2024-01-19').toISOString(),
        },
        {
            diet_chart_id: 5,
            meal_type: 'mid_morning',
            meal_time: '10:30 AM',
            total_calories: 160.0,
            total_protein: 6.4,
            total_carbs: 21.3,
            total_fat: 5.3,
            created_at: new Date('2024-01-19').toISOString(),
        },
        {
            diet_chart_id: 5,
            meal_type: 'lunch',
            meal_time: '1:00 PM',
            total_calories: 560.0,
            total_protein: 22.4,
            total_carbs: 74.7,
            total_fat: 18.7,
            created_at: new Date('2024-01-19').toISOString(),
        },
        {
            diet_chart_id: 5,
            meal_type: 'evening',
            meal_time: '4:30 PM',
            total_calories: 160.0,
            total_protein: 6.4,
            total_carbs: 21.3,
            total_fat: 5.3,
            created_at: new Date('2024-01-19').toISOString(),
        },
        {
            diet_chart_id: 5,
            meal_type: 'dinner',
            meal_time: '7:30 PM',
            total_calories: 320.0,
            total_protein: 12.8,
            total_carbs: 42.7,
            total_fat: 10.7,
            created_at: new Date('2024-01-19').toISOString(),
        }
    ];

    await db.insert(meals).values(sampleMeals);
    
    console.log('✅ Meals seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});