import { db } from '@/db';
import { meal_foods } from '@/db/schema';

async function main() {
    const sampleMealFoods = [
        // Meal 1 - Early Morning (6:00 AM) - Breakfast
        {
            meal_id: 1,
            food_name: 'Steel Cut Oats',
            quantity: 50,
            unit: 'g',
            calories: 185,
            protein: 6.5,
            carbs: 32,
            fat: 3.5,
            thermal_property: 'Warm',
            digestibility: 'Easy',
            rasa: '["Sweet", "Astringent"]',
            dosha_effect: 'Balances Vata, Neutral for Pitta, Reduces Kapha',
            created_at: new Date('2024-01-15').toISOString(),
        },
        {
            meal_id: 1,
            food_name: 'Soaked Almonds',
            quantity: 10,
            unit: 'pieces',
            calories: 70,
            protein: 2.6,
            carbs: 2.6,
            fat: 6.1,
            thermal_property: 'Hot',
            digestibility: 'Medium',
            rasa: '["Sweet"]',
            dosha_effect: 'Balances Vata, Neutral for Pitta, Increases Kapha',
            created_at: new Date('2024-01-15').toISOString(),
        },
        {
            meal_id: 1,
            food_name: 'Cow Ghee',
            quantity: 1,
            unit: 'tbsp',
            calories: 112,
            protein: 0,
            carbs: 0,
            fat: 12.8,
            thermal_property: 'Warm',
            digestibility: 'Easy',
            rasa: '["Sweet"]',
            dosha_effect: 'Balances Vata, Balances Pitta, Neutral for Kapha',
            created_at: new Date('2024-01-15').toISOString(),
        },
        {
            meal_id: 1,
            food_name: 'Raw Honey',
            quantity: 1,
            unit: 'tsp',
            calories: 21,
            protein: 0,
            carbs: 5.7,
            fat: 0,
            thermal_property: 'Hot',
            digestibility: 'Easy',
            rasa: '["Sweet"]',
            dosha_effect: 'Balances Vata, Increases Pitta, Reduces Kapha',
            created_at: new Date('2024-01-15').toISOString(),
        },

        // Meal 2 - Mid Morning (9:00 AM) - Snack
        {
            meal_id: 2,
            food_name: 'Tulsi Herbal Tea',
            quantity: 200,
            unit: 'ml',
            calories: 5,
            protein: 0,
            carbs: 1.2,
            fat: 0,
            thermal_property: 'Hot',
            digestibility: 'Easy',
            rasa: '["Pungent", "Bitter"]',
            dosha_effect: 'Balances Vata, Balances Pitta, Reduces Kapha',
            created_at: new Date('2024-01-15').toISOString(),
        },
        {
            meal_id: 2,
            food_name: 'Fresh Dates',
            quantity: 2,
            unit: 'pieces',
            calories: 40,
            protein: 0.4,
            carbs: 10.7,
            fat: 0.1,
            thermal_property: 'Warm',
            digestibility: 'Easy',
            rasa: '["Sweet"]',
            dosha_effect: 'Balances Vata, Neutral for Pitta, Increases Kapha',
            created_at: new Date('2024-01-15').toISOString(),
        },
        {
            meal_id: 2,
            food_name: 'Walnuts',
            quantity: 4,
            unit: 'pieces',
            calories: 52,
            protein: 1.2,
            carbs: 1.1,
            fat: 5.2,
            thermal_property: 'Hot',
            digestibility: 'Difficult',
            rasa: '["Sweet", "Astringent"]',
            dosha_effect: 'Balances Vata, Increases Pitta, Increases Kapha',
            created_at: new Date('2024-01-15').toISOString(),
        },

        // Meal 3 - Lunch (12:00 PM)
        {
            meal_id: 3,
            food_name: 'Basmati Rice',
            quantity: 100,
            unit: 'g',
            calories: 130,
            protein: 2.7,
            carbs: 28,
            fat: 0.3,
            thermal_property: 'Cool',
            digestibility: 'Easy',
            rasa: '["Sweet"]',
            dosha_effect: 'Neutral for Vata, Balances Pitta, Increases Kapha',
            created_at: new Date('2024-01-15').toISOString(),
        },
        {
            meal_id: 3,
            food_name: 'Moong Dal',
            quantity: 60,
            unit: 'g',
            calories: 210,
            protein: 14.2,
            carbs: 35,
            fat: 1.2,
            thermal_property: 'Cool',
            digestibility: 'Easy',
            rasa: '["Sweet", "Astringent"]',
            dosha_effect: 'Balances Vata, Balances Pitta, Reduces Kapha',
            created_at: new Date('2024-01-15').toISOString(),
        },
        {
            meal_id: 3,
            food_name: 'Bottle Gourd Curry',
            quantity: 150,
            unit: 'g',
            calories: 45,
            protein: 1.8,
            carbs: 8.5,
            fat: 0.8,
            thermal_property: 'Cool',
            digestibility: 'Easy',
            rasa: '["Sweet", "Bitter"]',
            dosha_effect: 'Balances Vata, Balances Pitta, Reduces Kapha',
            created_at: new Date('2024-01-15').toISOString(),
        },
        {
            meal_id: 3,
            food_name: 'Whole Wheat Chapati',
            quantity: 2,
            unit: 'pieces',
            calories: 140,
            protein: 5.4,
            carbs: 28,
            fat: 1.8,
            thermal_property: 'Warm',
            digestibility: 'Medium',
            rasa: '["Sweet"]',
            dosha_effect: 'Balances Vata, Neutral for Pitta, Increases Kapha',
            created_at: new Date('2024-01-15').toISOString(),
        },
        {
            meal_id: 3,
            food_name: 'Cucumber Salad',
            quantity: 80,
            unit: 'g',
            calories: 12,
            protein: 0.5,
            carbs: 2.8,
            fat: 0.1,
            thermal_property: 'Cool',
            digestibility: 'Easy',
            rasa: '["Sweet", "Astringent"]',
            dosha_effect: 'Neutral for Vata, Balances Pitta, Reduces Kapha',
            created_at: new Date('2024-01-15').toISOString(),
        },

        // Meal 4 - Evening Snack (4:00 PM)
        {
            meal_id: 4,
            food_name: 'Ginger Tea',
            quantity: 200,
            unit: 'ml',
            calories: 8,
            protein: 0,
            carbs: 2,
            fat: 0,
            thermal_property: 'Hot',
            digestibility: 'Easy',
            rasa: '["Pungent", "Sweet"]',
            dosha_effect: 'Balances Vata, Neutral for Pitta, Reduces Kapha',
            created_at: new Date('2024-01-15').toISOString(),
        },
        {
            meal_id: 4,
            food_name: 'Roasted Chickpeas',
            quantity: 30,
            unit: 'g',
            calories: 105,
            protein: 5.7,
            carbs: 17.7,
            fat: 1.7,
            thermal_property: 'Warm',
            digestibility: 'Medium',
            rasa: '["Sweet", "Astringent"]',
            dosha_effect: 'Balances Vata, Neutral for Pitta, Reduces Kapha',
            created_at: new Date('2024-01-15').toISOString(),
        },

        // Meal 5 - Dinner (7:00 PM)
        {
            meal_id: 5,
            food_name: 'Multigrain Chapati',
            quantity: 1,
            unit: 'piece',
            calories: 80,
            protein: 3.2,
            carbs: 16,
            fat: 1.2,
            thermal_property: 'Warm',
            digestibility: 'Medium',
            rasa: '["Sweet"]',
            dosha_effect: 'Balances Vata, Neutral for Pitta, Neutral for Kapha',
            created_at: new Date('2024-01-15').toISOString(),
        },
        {
            meal_id: 5,
            food_name: 'Palak Sabzi',
            quantity: 100,
            unit: 'g',
            calories: 35,
            protein: 3.2,
            carbs: 4.3,
            fat: 0.7,
            thermal_property: 'Cool',
            digestibility: 'Easy',
            rasa: '["Sweet", "Bitter", "Astringent"]',
            dosha_effect: 'Balances Vata, Balances Pitta, Reduces Kapha',
            created_at: new Date('2024-01-15').toISOString(),
        },
        {
            meal_id: 5,
            food_name: 'Masoor Dal',
            quantity: 40,
            unit: 'g',
            calories: 145,
            protein: 9.8,
            carbs: 25,
            fat: 0.6,
            thermal_property: 'Warm',
            digestibility: 'Easy',
            rasa: '["Sweet", "Astringent"]',
            dosha_effect: 'Balances Vata, Neutral for Pitta, Reduces Kapha',
            created_at: new Date('2024-01-15').toISOString(),
        },

        // Meal 6 - Early Morning (6:00 AM) - Breakfast
        {
            meal_id: 6,
            food_name: 'Poha',
            quantity: 60,
            unit: 'g',
            calories: 210,
            protein: 4.8,
            carbs: 46.8,
            fat: 1.2,
            thermal_property: 'Warm',
            digestibility: 'Easy',
            rasa: '["Sweet"]',
            dosha_effect: 'Balances Vata, Neutral for Pitta, Increases Kapha',
            created_at: new Date('2024-01-16').toISOString(),
        },
        {
            meal_id: 6,
            food_name: 'Curry Leaves',
            quantity: 5,
            unit: 'g',
            calories: 3,
            protein: 0.3,
            carbs: 0.5,
            fat: 0.1,
            thermal_property: 'Hot',
            digestibility: 'Easy',
            rasa: '["Pungent", "Bitter"]',
            dosha_effect: 'Balances Vata, Neutral for Pitta, Reduces Kapha',
            created_at: new Date('2024-01-16').toISOString(),
        },
        {
            meal_id: 6,
            food_name: 'Coconut',
            quantity: 15,
            unit: 'g',
            calories: 53,
            protein: 0.5,
            carbs: 2.3,
            fat: 5.1,
            thermal_property: 'Cool',
            digestibility: 'Medium',
            rasa: '["Sweet"]',
            dosha_effect: 'Balances Vata, Balances Pitta, Increases Kapha',
            created_at: new Date('2024-01-16').toISOString(),
        },

        // Meal 7 - Mid Morning (9:00 AM)
        {
            meal_id: 7,
            food_name: 'Cardamom Tea',
            quantity: 200,
            unit: 'ml',
            calories: 10,
            protein: 0,
            carbs: 2.5,
            fat: 0,
            thermal_property: 'Warm',
            digestibility: 'Easy',
            rasa: '["Sweet", "Pungent"]',
            dosha_effect: 'Balances Vata, Balances Pitta, Reduces Kapha',
            created_at: new Date('2024-01-16').toISOString(),
        },
        {
            meal_id: 7,
            food_name: 'Raisins',
            quantity: 20,
            unit: 'g',
            calories: 60,
            protein: 0.6,
            carbs: 15.8,
            fat: 0.1,
            thermal_property: 'Warm',
            digestibility: 'Easy',
            rasa: '["Sweet", "Sour"]',
            dosha_effect: 'Balances Vata, Neutral for Pitta, Increases Kapha',
            created_at: new Date('2024-01-16').toISOString(),
        },

        // Meal 8 - Lunch (12:00 PM)
        {
            meal_id: 8,
            food_name: 'Brown Rice',
            quantity: 80,
            unit: 'g',
            calories: 280,
            protein: 5.6,
            carbs: 58.4,
            fat: 2.2,
            thermal_property: 'Warm',
            digestibility: 'Medium',
            rasa: '["Sweet"]',
            dosha_effect: 'Balances Vata, Neutral for Pitta, Neutral for Kapha',
            created_at: new Date('2024-01-16').toISOString(),
        },
        {
            meal_id: 8,
            food_name: 'Toor Dal',
            quantity: 50,
            unit: 'g',
            calories: 175,
            protein: 11.5,
            carbs: 29,
            fat: 1,
            thermal_property: 'Warm',
            digestibility: 'Easy',
            rasa: '["Sweet", "Astringent"]',
            dosha_effect: 'Balances Vata, Neutral for Pitta, Reduces Kapha',
            created_at: new Date('2024-01-16').toISOString(),
        },
        {
            meal_id: 8,
            food_name: 'Okra Curry',
            quantity: 120,
            unit: 'g',
            calories: 40,
            protein: 2.4,
            carbs: 8.4,
            fat: 0.2,
            thermal_property: 'Warm',
            digestibility: 'Medium',
            rasa: '["Sweet"]',
            dosha_effect: 'Balances Vata, Neutral for Pitta, Reduces Kapha',
            created_at: new Date('2024-01-16').toISOString(),
        },
        {
            meal_id: 8,
            food_name: 'Buttermilk',
            quantity: 150,
            unit: 'ml',
            calories: 45,
            protein: 2.3,
            carbs: 5.2,
            fat: 1.4,
            thermal_property: 'Cool',
            digestibility: 'Easy',
            rasa: '["Sweet", "Sour", "Astringent"]',
            dosha_effect: 'Neutral for Vata, Balances Pitta, Reduces Kapha',
            created_at: new Date('2024-01-16').toISOString(),
        },

        // Meal 9 - Evening Snack (4:00 PM)
        {
            meal_id: 9,
            food_name: 'Fennel Tea',
            quantity: 200,
            unit: 'ml',
            calories: 6,
            protein: 0,
            carbs: 1.5,
            fat: 0,
            thermal_property: 'Cool',
            digestibility: 'Easy',
            rasa: '["Sweet", "Pungent"]',
            dosha_effect: 'Balances Vata, Balances Pitta, Reduces Kapha',
            created_at: new Date('2024-01-16').toISOString(),
        },
        {
            meal_id: 9,
            food_name: 'Seasonal Fruits',
            quantity: 100,
            unit: 'g',
            calories: 55,
            protein: 0.8,
            carbs: 14,
            fat: 0.2,
            thermal_property: 'Cool',
            digestibility: 'Easy',
            rasa: '["Sweet", "Sour"]',
            dosha_effect: 'Neutral for Vata, Balances Pitta, Neutral for Kapha',
            created_at: new Date('2024-01-16').toISOString(),
        },

        // Meal 10 - Dinner (7:00 PM)
        {
            meal_id: 10,
            food_name: 'Bajra Roti',
            quantity: 1,
            unit: 'piece',
            calories: 90,
            protein: 3.6,
            carbs: 17,
            fat: 1.8,
            thermal_property: 'Hot',
            digestibility: 'Medium',
            rasa: '["Sweet"]',
            dosha_effect: 'Balances Vata, Neutral for Pitta, Reduces Kapha',
            created_at: new Date('2024-01-16').toISOString(),
        },
        {
            meal_id: 10,
            food_name: 'Ridge Gourd Curry',
            quantity: 100,
            unit: 'g',
            calories: 25,
            protein: 1.2,
            carbs: 5.5,
            fat: 0.2,
            thermal_property: 'Cool',
            digestibility: 'Easy',
            rasa: '["Sweet", "Bitter"]',
            dosha_effect: 'Balances Vata, Balances Pitta, Reduces Kapha',
            created_at: new Date('2024-01-16').toISOString(),
        },
        {
            meal_id: 10,
            food_name: 'Chana Dal',
            quantity: 40,
            unit: 'g',
            calories: 140,
            protein: 8.8,
            carbs: 24,
            fat: 2.4,
            thermal_property: 'Warm',
            digestibility: 'Medium',
            rasa: '["Sweet", "Astringent"]',
            dosha_effect: 'Balances Vata, Neutral for Pitta, Reduces Kapha',
            created_at: new Date('2024-01-16').toISOString(),
        },

        // Continue with remaining meals (11-25) following similar pattern
        // Meal 11 - Breakfast
        {
            meal_id: 11,
            food_name: 'Upma',
            quantity: 80,
            unit: 'g',
            calories: 195,
            protein: 4.8,
            carbs: 38,
            fat: 3.2,
            thermal_property: 'Warm',
            digestibility: 'Easy',
            rasa: '["Sweet"]',
            dosha_effect: 'Balances Vata, Neutral for Pitta, Neutral for Kapha',
            created_at: new Date('2024-01-17').toISOString(),
        },
        {
            meal_id: 11,
            food_name: 'Mustard Seeds',
            quantity: 2,
            unit: 'g',
            calories: 10,
            protein: 0.5,
            carbs: 0.6,
            fat: 0.8,
            thermal_property: 'Hot',
            digestibility: 'Medium',
            rasa: '["Pungent"]',
            dosha_effect: 'Balances Vata, Increases Pitta, Reduces Kapha',
            created_at: new Date('2024-01-17').toISOString(),
        },
        {
            meal_id: 11,
            food_name: 'Cashews',
            quantity: 8,
            unit: 'pieces',
            calories: 44,
            protein: 1.5,
            carbs: 2.4,
            fat: 3.6,
            thermal_property: 'Hot',
            digestibility: 'Medium',
            rasa: '["Sweet"]',
            dosha_effect: 'Balances Vata, Increases Pitta, Increases Kapha',
            created_at: new Date('2024-01-17').toISOString(),
        },

        // Meal 12 - Mid Morning
        {
            meal_id: 12,
            food_name: 'Mint Tea',
            quantity: 200,
            unit: 'ml',
            calories: 4,
            protein: 0,
            carbs: 1,
            fat: 0,
            thermal_property: 'Cool',
            digestibility: 'Easy',
            rasa: '["Pungent", "Sweet"]',
            dosha_effect: 'Balances Vata, Balances Pitta, Reduces Kapha',
            created_at: new Date('2024-01-17').toISOString(),
        },
        {
            meal_id: 12,
            food_name: 'Dried Figs',
            quantity: 2,
            unit: 'pieces',
            calories: 47,
            protein: 0.8,
            carbs: 12.2,
            fat: 0.2,
            thermal_property: 'Warm',
            digestibility: 'Easy',
            rasa: '["Sweet"]',
            dosha_effect: 'Balances Vata, Neutral for Pitta, Increases Kapha',
            created_at: new Date('2024-01-17').toISOString(),
        },

        // Meal 13 - Lunch
        {
            meal_id: 13,
            food_name: 'Quinoa',
            quantity: 70,
            unit: 'g',
            calories: 255,
            protein: 9.1,
            carbs: 46.2,
            fat: 4.2,
            thermal_property: 'Warm',
            digestibility: 'Easy',
            rasa: '["Sweet"]',
            dosha_effect: 'Balances Vata, Neutral for Pitta, Neutral for Kapha',
            created_at: new Date('2024-01-17').toISOString(),
        },
        {
            meal_id: 13,
            food_name: 'Urad Dal',
            quantity: 45,
            unit: 'g',
            calories: 160,
            protein: 10.8,
            carbs: 26.1,
            fat: 1.4,
            thermal_property: 'Hot',
            digestibility: 'Medium',
            rasa: '["Sweet", "Astringent"]',
            dosha_effect: 'Balances Vata, Increases Pitta, Increases Kapha',
            created_at: new Date('2024-01-17').toISOString(),
        },
        {
            meal_id: 13,
            food_name: 'Drumstick Curry',
            quantity: 100,
            unit: 'g',
            calories: 30,
            protein: 2.1,
            carbs: 5.7,
            fat: 0.2,
            thermal_property: 'Warm',
            digestibility: 'Easy',
            rasa: '["Sweet", "Pungent"]',
            dosha_effect: 'Balances Vata, Neutral for Pitta, Reduces Kapha',
            created_at: new Date('2024-01-17').toISOString(),
        },
        {
            meal_id: 13,
            food_name: 'Millet Roti',
            quantity: 1,
            unit: 'piece',
            calories: 85,
            protein: 3.2,
            carbs: 16.8,
            fat: 1.4,
            thermal_property: 'Warm',
            digestibility: 'Medium',
            rasa: '["Sweet"]',
            dosha_effect: 'Balances Vata, Neutral for Pitta, Reduces Kapha',
            created_at: new Date('2024-01-17').toISOString(),
        },

        // Meal 14 - Evening Snack
        {
            meal_id: 14,
            food_name: 'Cumin Tea',
            quantity: 200,
            unit: 'ml',
            calories: 8,
            protein: 0.4,
            carbs: 1.8,
            fat: 0,
            thermal_property: 'Warm',
            digestibility: 'Easy',
            rasa: '["Pungent", "Bitter"]',
            dosha_effect: 'Balances Vata, Neutral for Pitta, Reduces Kapha',
            created_at: new Date('2024-01-17').toISOString(),
        },
        {
            meal_id: 14,
            food_name: 'Roasted Makhana',
            quantity: 25,
            unit: 'g',
            calories: 87,
            protein: 3.9,
            carbs: 17.2,
            fat: 0.1,
            thermal_property: 'Cool',
            digestibility: 'Easy',
            rasa: '["Sweet", "Astringent"]',
            dosha_effect: 'Balances Vata, Balances Pitta, Reduces Kapha',
            created_at: new Date('2024-01-17').toISOString(),
        },

        // Meal 15 - Dinner
        {
            meal_id: 15,
            food_name: 'Jowar Roti',
            quantity: 1,
            unit: 'piece',
            calories: 75,
            protein: 2.8,
            carbs: 15.5,
            fat: 1.2,
            thermal_property: 'Warm',
            digestibility: 'Medium',
            rasa: '["Sweet"]',
            dosha_effect: 'Balances Vata, Neutral for Pitta, Reduces Kapha',
            created_at: new Date('2024-01-17').toISOString(),
        },
        {
            meal_id: 15,
            food_name: 'Cabbage Sabzi',
            quantity: 120,
            unit: 'g',
            calories: 30,
            protein: 1.4,
            carbs: 7,
            fat: 0.1,
            thermal_property: 'Warm',
            digestibility: 'Medium',
            rasa: '["Sweet", "Pungent"]',
            dosha_effect: 'Balances Vata, Neutral for Pitta, Reduces Kapha',
            created_at: new Date('2024-01-17').toISOString(),
        },
        {
            meal_id: 15,
            food_name: 'Kulthi Dal',
            quantity: 35,
            unit: 'g',
            calories: 120,
            protein: 8.4,
            carbs: 20.3,
            fat: 0.7,
            thermal_property: 'Hot',
            digestibility: 'Difficult',
            rasa: '["Sweet", "Astringent"]',
            dosha_effect: 'Balances Vata, Increases Pitta, Reduces Kapha',
            created_at: new Date('2024-01-17').toISOString(),
        },

        // Continue with more diverse food items for remaining meals
        // Adding variety in food names, thermal properties, and nutritional values

        // Meal 16 - Breakfast
        {
            meal_id: 16,
            food_name: 'Idli',
            quantity: 3,
            unit: 'pieces',
            calories: 156,
            protein: 4.2,
            carbs: 30,
            fat: 2.1,
            thermal_property: 'Cool',
            digestibility: 'Easy',
            rasa: '["Sweet", "Sour"]',
            dosha_effect: 'Balances Vata, Balances Pitta, Neutral for Kapha',
            created_at: new Date('2024-01-18').toISOString(),
        },
        {
            meal_id: 16,
            food_name: 'Coconut Chutney',
            quantity: 30,
            unit: 'g',
            calories: 85,
            protein: 1.2,
            carbs: 3.8,
            fat: 8.2,
            thermal_property: 'Cool',
            digestibility: 'Medium',
            rasa: '["Sweet"]',
            dosha_effect: 'Balances Vata, Balances Pitta, Increases Kapha',
            created_at: new Date('2024-01-18').toISOString(),
        },
        {
            meal_id: 16,
            food_name: 'Sambar',
            quantity: 100,
            unit: 'ml',
            calories: 65,
            protein: 3.2,
            carbs: 10.5,
            fat: 1.8,
            thermal_property: 'Warm',
            digestibility: 'Easy',
            rasa: '["Sweet", "Sour", "Pungent"]',
            dosha_effect: 'Balances Vata, Neutral for Pitta, Reduces Kapha',
            created_at: new Date('2024-01-18').toISOString(),
        },

        // Meal 17 - Mid Morning
        {
            meal_id: 17,
            food_name: 'Coriander Seed Tea',
            quantity: 200,
            unit: 'ml',
            calories: 6,
            protein: 0.2,
            carbs: 1.4,
            fat: 0,
            thermal_property: 'Cool',
            digestibility: 'Easy',
            rasa: '["Sweet", "Pungent"]',
            dosha_effect: 'Balances Vata, Balances Pitta, Reduces Kapha',
            created_at: new Date('2024-01-18').toISOString(),
        },
        {
            meal_id: 17,
            food_name: 'Pomegranate',
            quantity: 80,
            unit: 'g',
            calories: 66,
            protein: 1.3,
            carbs: 16.6,
            fat: 0.9,
            thermal_property: 'Cool',
            digestibility: 'Easy',
            rasa: '["Sweet", "Sour", "Astringent"]',
            dosha_effect: 'Neutral for Vata, Balances Pitta, Reduces Kapha',
            created_at: new Date('2024-01-18').toISOString(),
        },

        // Additional meal foods to reach 100+ items
        // Meal 18 - Lunch
        {
            meal_id: 18,
            food_name: 'Red Rice',
            quantity: 90,
            unit: 'g',
            calories: 320,
            protein: 7.2,
            carbs: 68.4,
            fat: 2.7,
            thermal_property: 'Warm',
            digestibility: 'Medium',
            rasa: '["Sweet"]',
            dosha_effect: 'Balances Vata, Neutral for Pitta, Neutral for Kapha',
            created_at: new Date('2024-01-18').toISOString(),
        },
        {
            meal_id: 18,
            food_name: 'Rajma',
            quantity: 50,
            unit: 'g',
            calories: 165,
            protein: 11.5,
            carbs: 28,
            fat: 0.8,
            thermal_property: 'Warm',
            digestibility: 'Difficult',
            rasa: '["Sweet", "Astringent"]',
            dosha_effect: 'Balances Vata, Neutral for Pitta, Neutral for Kapha',
            created_at: new Date('2024-01-18').toISOString(),
        },
        {
            meal_id: 18,
            food_name: 'Karela Sabzi',
            quantity: 100,
            unit: 'g',
            calories: 25,
            protein: 1.8,
            carbs: 5.6,
            fat: 0.2,
            thermal_property: 'Cool',
            digestibility: 'Medium',
            rasa: '["Bitter"]',
            dosha_effect: 'Neutral for Vata, Balances Pitta, Reduces Kapha',
            created_at: new Date('2024-01-18').toISOString(),
        },

        // Meal 19 - Evening Snack
        {
            meal_id: 19,
            food_name: 'Ajwain Tea',
            quantity: 200,
            unit: 'ml',
            calories: 5,
            protein: 0.1,
            carbs: 1.2,
            fat: 0,
            thermal_property: 'Hot',
            digestibility: 'Easy',
            rasa: '["Pungent", "Bitter"]',
            dosha_effect: 'Balances Vata, Neutral for Pitta, Reduces Kapha',
            created_at: new Date('2024-01-18').toISOString(),
        },
        {
            meal_id: 19,
            food_name: 'Til Laddu',
            quantity: 1,
            unit: 'piece',
            calories: 95,
            protein: 2.8,
            carbs: 8.5,
            fat: 6.2,
            thermal_property: 'Hot',
            digestibility: 'Medium',
            rasa: '["Sweet"]',
            dosha_effect: 'Balances Vata, Increases Pitta, Neutral for Kapha',
            created_at: new Date('2024-01-18').toISOString(),
        },

        // Meal 20 - Dinner
        {
            meal_id: 20,
            food_name: 'Amaranth Roti',
            quantity: 1,
            unit: 'piece',
            calories: 70,
            protein: 2.8,
            carbs: 13.5,
            fat: 1.2,
            thermal_property: 'Warm',
            digestibility: 'Medium',
            rasa: '["Sweet"]',
            dosha_effect: 'Balances Vata, Neutral for Pitta, Reduces Kapha',
            created_at: new Date('2024-01-18').toISOString(),
        },
        {
            meal_id: 20,
            food_name: 'Lauki Dal',
            quantity: 120,
            unit: 'g',
            calories: 85,
            protein: 5.2,
            carbs: 14.8,
            fat: 1.1,
            thermal_property: 'Cool',
            digestibility: 'Easy',
            rasa: '["Sweet"]',
            dosha_effect: 'Balances Vata, Balances Pitta, Reduces Kapha',
            created_at: new Date('2024-01-18').toISOString(),
        },

        // Final meals with remaining diverse foods
        // Meal 21-25 foods
        {
            meal_id: 21,
            food_name: 'Khichdi',
            quantity: 100,
            unit: 'g',
            calories: 120,
            protein: 4.8,
            carbs: 22.5,
            fat: 1.2,
            thermal_property: 'Warm',
            digestibility: 'Easy',
            rasa: '["Sweet"]',
            dosha_effect: 'Balances Vata, Balances Pitta, Neutral for Kapha',
            created_at: new Date('2024-01-19').toISOString(),
        },
        {
            meal_id: 22,
            food_name: 'Methi Paratha',
            quantity: 1,
            unit: 'piece',
            calories: 110,
            protein: 4.2,
            carbs: 18.5,
            fat: 2.8,
            thermal_property: 'Hot',
            digestibility: 'Medium',
            rasa: '["Bitter", "Pungent"]',
            dosha_effect: 'Balances Vata, Increases Pitta, Reduces Kapha',
            created_at: new Date('2024-01-19').toISOString(),
        },
        {
            meal_id: 23,
            food_name: 'Beetroot Salad',
            quantity: 70,
            unit: 'g',
            calories: 30,
            protein: 1.2,
            carbs: 7.2,
            fat: 0.1,
            thermal_property: 'Cool',
            digestibility: 'Easy',
            rasa: '["Sweet"]',
            dosha_effect: 'Neutral for Vata, Balances Pitta, Reduces Kapha',
            created_at: new Date('2024-01-19').toISOString(),
        },
        {
            meal_id: 24,
            food_name: 'Mung Bean Sprouts',
            quantity: 60,
            unit: 'g',
            calories: 18,
            protein: 1.8,
            carbs: 3.6,
            fat: 0.1,
            thermal_property: 'Cool',
            digestibility: 'Easy',
            rasa: '["Sweet", "Astringent"]',
            dosha_effect: 'Balances Vata, Balances Pitta, Reduces Kapha',
            created_at: new Date('2024-01-19').toISOString(),
        },
        {
            meal_id: 25,
            food_name: 'Ashwagandha Milk',
            quantity: 200,
            unit: 'ml',
            calories: 110,
            protein: 6.2,
            carbs: 9.8,
            fat: 5.2,
            thermal_property: 'Warm',
            digestibility: 'Easy',
            rasa: '["Sweet", "Bitter"]',
            dosha_effect: 'Balances Vata, Neutral for Pitta, Neutral for Kapha',
            created_at: new Date('2024-01-19').toISOString(),
        }
    ];

    await db.insert(meal_foods).values(sampleMealFoods);
    
    console.log('✅ Meal foods seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});