import { db } from '@/db';
import { patients } from '@/db/schema';

async function main() {
    const samplePatients = [
        {
            name: 'Priya Sharma',
            age: 32,
            gender: 'Female',
            dosha: 'Vata',
            phone: '+91-9876543210',
            email: 'priya.sharma@gmail.com',
            height: 162.0,
            weight: 52.0,
            bmi: 19.8,
            dietary_habits: 'Vegetarian',
            meal_frequency: 5,
            water_intake: 2.5,
            health_conditions: 'Anxiety, Digestive issues',
            allergies: 'Nuts',
            notes: 'Patient has been experiencing anxiety and irregular digestion patterns. Prefers lighter meals and needs guidance on Vata-pacifying foods. Shows good compliance with dietary recommendations.',
            status: 'Active',
            created_at: new Date('2024-01-15').toISOString(),
            updated_at: new Date('2024-01-15').toISOString(),
        },
        {
            name: 'Rajesh Kumar',
            age: 45,
            gender: 'Male',
            dosha: 'Pitta',
            phone: '+91-9123456789',
            email: 'rajesh.kumar@outlook.com',
            height: 175.0,
            weight: 78.0,
            bmi: 25.5,
            dietary_habits: 'Non-vegetarian',
            meal_frequency: 4,
            water_intake: 3.0,
            health_conditions: 'Hypertension, Acidity',
            allergies: 'Dairy',
            notes: 'Executive with high stress levels and irregular eating patterns. Needs cooling foods to balance excess Pitta. Has shown improvement in blood pressure with dietary modifications.',
            status: 'Active',
            created_at: new Date('2024-01-20').toISOString(),
            updated_at: new Date('2024-01-20').toISOString(),
        },
        {
            name: 'Meena Iyer',
            age: 38,
            gender: 'Female',
            dosha: 'Kapha',
            phone: '+91-9234567890',
            email: 'meena.iyer@yahoo.com',
            height: 158.0,
            weight: 68.0,
            bmi: 27.2,
            dietary_habits: 'Vegetarian',
            meal_frequency: 3,
            water_intake: 2.0,
            health_conditions: 'Diabetes Type 2, Hypothyroidism',
            allergies: 'Gluten',
            notes: 'Struggling with weight management and blood sugar control. Needs metabolism-boosting foods and regular meal timing. Recently started following gluten-free diet with positive results.',
            status: 'Active',
            created_at: new Date('2024-02-01').toISOString(),
            updated_at: new Date('2024-02-01').toISOString(),
        },
        {
            name: 'Arjun Patel',
            age: 29,
            gender: 'Male',
            dosha: 'Vata',
            phone: '+91-9345678901',
            email: 'arjun.patel@gmail.com',
            height: 180.0,
            weight: 65.0,
            bmi: 20.1,
            dietary_habits: 'Vegan',
            meal_frequency: 6,
            water_intake: 3.5,
            health_conditions: 'Chronic fatigue, Joint pain',
            allergies: null,
            notes: 'Young professional with irregular sleep patterns and low energy levels. Following plant-based diet and needs grounding, nourishing foods to support Vata constitution.',
            status: 'Active',
            created_at: new Date('2024-02-05').toISOString(),
            updated_at: new Date('2024-02-05').toISOString(),
        },
        {
            name: 'Sunita Reddy',
            age: 42,
            gender: 'Female',
            dosha: 'Pitta',
            phone: '+91-9456789012',
            email: 'sunita.reddy@hotmail.com',
            height: 165.0,
            weight: 58.0,
            bmi: 21.3,
            dietary_habits: 'Vegetarian',
            meal_frequency: 4,
            water_intake: 3.2,
            health_conditions: 'PCOD, Irregular periods',
            allergies: 'Dairy',
            notes: 'Dealing with hormonal imbalances and seeking natural dietary solutions. Responds well to cooling herbs and regular meal timings. Has shown improvement in cycle regularity.',
            status: 'Active',
            created_at: new Date('2024-02-10').toISOString(),
            updated_at: new Date('2024-02-10').toISOString(),
        },
        {
            name: 'Vikram Singh',
            age: 51,
            gender: 'Male',
            dosha: 'Kapha',
            phone: '+91-9567890123',
            email: 'vikram.singh@gmail.com',
            height: 172.0,
            weight: 85.0,
            bmi: 28.7,
            dietary_habits: 'Non-vegetarian',
            meal_frequency: 3,
            water_intake: 2.8,
            health_conditions: 'High cholesterol, Arthritis',
            allergies: null,
            notes: 'Middle-aged patient with sedentary lifestyle and joint issues. Needs warming spices and lighter foods. Has been making gradual progress with dietary changes and increased activity.',
            status: 'Active',
            created_at: new Date('2024-02-15').toISOString(),
            updated_at: new Date('2024-02-15').toISOString(),
        },
        {
            name: 'Kavya Nair',
            age: 35,
            gender: 'Female',
            dosha: 'Vata',
            phone: '+91-9678901234',
            email: 'kavya.nair@outlook.com',
            height: 160.0,
            weight: 48.0,
            bmi: 18.8,
            dietary_habits: 'Vegetarian',
            meal_frequency: 5,
            water_intake: 2.2,
            health_conditions: 'Insomnia, Dry skin',
            allergies: 'Nuts, Gluten',
            notes: 'Creative professional with irregular schedules and difficulty maintaining weight. Requires nourishing, easily digestible foods and consistent meal timing to ground Vata energy.',
            status: 'Inactive',
            created_at: new Date('2024-01-25').toISOString(),
            updated_at: new Date('2024-01-25').toISOString(),
        },
        {
            name: 'Amit Joshi',
            age: 47,
            gender: 'Male',
            dosha: 'Vata-Pitta',
            phone: '+91-9789012345',
            email: 'amit.joshi@yahoo.com',
            height: 178.0,
            weight: 72.0,
            bmi: 22.7,
            dietary_habits: 'Eggetarian',
            meal_frequency: 4,
            water_intake: 3.8,
            health_conditions: 'Migraine, Acid reflux',
            allergies: 'Dairy',
            notes: 'Dual dosha constitution requiring balanced approach. Experiences both Vata irregularity and Pitta heat symptoms. Needs cooling yet grounding foods with regular meal patterns.',
            status: 'Active',
            created_at: new Date('2024-02-20').toISOString(),
            updated_at: new Date('2024-02-20').toISOString(),
        },
        {
            name: 'Deepika Agarwal',
            age: 28,
            gender: 'Female',
            dosha: 'Pitta-Kapha',
            phone: '+91-9890123456',
            email: 'deepika.agarwal@gmail.com',
            height: 155.0,
            weight: 61.0,
            bmi: 25.4,
            dietary_habits: 'Vegetarian',
            meal_frequency: 3,
            water_intake: 2.7,
            health_conditions: 'Weight gain, Slow digestion',
            allergies: null,
            notes: 'Young woman with combination constitution showing both Pitta intensity and Kapha heaviness. Needs metabolism-boosting foods that are also cooling. Making steady progress with portion control.',
            status: 'Active',
            created_at: new Date('2024-02-25').toISOString(),
            updated_at: new Date('2024-02-25').toISOString(),
        },
        {
            name: 'Ramesh Gupta',
            age: 60,
            gender: 'Male',
            dosha: 'Kapha-Vata',
            phone: '+91-9901234567',
            email: 'ramesh.gupta@hotmail.com',
            height: 170.0,
            weight: 75.0,
            bmi: 26.0,
            dietary_habits: 'Vegetarian',
            meal_frequency: 4,
            water_intake: 2.4,
            health_conditions: 'Diabetes, Joint stiffness, Memory issues',
            allergies: 'Nuts',
            notes: 'Senior patient with age-related Vata increase over primary Kapha constitution. Requires warm, easily digestible foods that support cognitive function and joint health. Family support available for meal compliance.',
            status: 'Inactive',
            created_at: new Date('2024-01-30').toISOString(),
            updated_at: new Date('2024-01-30').toISOString(),
        }
    ];

    await db.insert(patients).values(samplePatients);
    
    console.log('✅ Patients seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});